name: Core C CI

on:
  push:
    branches: [ master, github-ci ]
  pull_request:
    branches: [ master, github-ci ]

jobs:
  standard:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest]

    name: "💦 ${{ matrix.runs-on }}"
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup libfec
      run: https://github.com/jgaeddert/libfec.git && ./configure && make && sudo make install

    - name: bootstrap
      run: ./bootstrap.sh

    - name: configure
      run: ./configure

    - name: make
      run: make -j 2

    - name: make check
      run: make -j 2 check
