name: Python CI

on:
  push:
    branches: [ master, github-ci ]
  pull_request:
    branches: [ master, github-ci ]

jobs:
  standard:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest]

    name: "💦 ${{ matrix.runs-on }}"
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v2
    - name: bootstrap
      run: ./bootstrap.sh
    - name: configure
      run: ./configure
    - name: make python
      run: make -j 2 python
